### PR TITLE
Joystick_8 class makes it easier to use the stick

### PR DESCRIPTION
**Pull request by gdsports**
Thread-safe but not yet tested with threads.

To run the test program.

sudo python3 Joystick_8.py

To use in another program.

import Joystick_8

### CODE REVIEW

**Review by milador — COMMENTED** [review]
Can you provide more information about the code? is it to be used as a usb joystick connected to raspberry pi?

**Comment by gdsports** [comment]
Joystick_8 class hides the details of the implementation of the HID report.
The user calls functions such press and release for buttons.

8_buttons_joystick_usb must be run to create the Joystick_8 device.


```
    joystick = Joystick_8()
    joystick.begin('/dev/hidg0')

    while True:
        # Press and hold every button
        for button in range(0, 8):
            joystick.press(button)
            time.sleep(0.1)
        time.sleep(1)
        # Release all buttons
        joystick.releaseAll()
        time.sleep(1)
        # Press all buttons at the same time
        joystick.buttons(0xff)
        time.sleep(1)
        # Release all buttons
        joystick.releaseAll()
        time.sleep(1)
```

**Comment by milador** [comment]
Ok great I will try it and will accept the request. I probably need to add some instructions. I  will change the file name in the future as well but should be ok for now. BTW, I am hoping to test a new descriptor for XAC. I will get back to you regarding that. It would be great to have some help implementing the code for that one as well if it works. Thanks again

**Comment by gdsports** [comment]
I added a standalone demo program that uses the Joystick_8 class. It presses and releases all buttons then moves the stick clockwise. The file name is joystick_demo.py

Changing the names is fine with me.

I have been experimenting with HID gamepad descriptors that work with a Nintendo Switch. I learned a few things that might apply to the XAC so I will try again.

**Pull request merged**
