### PR TITLE
Create Http_Api.py

### PR DESCRIPTION
**Pull request by sam2332**
This is a http server with autogenerated doc via fastapi

### CODE REVIEW

**Comment by sam2332** [comment]
image

**Comment by milador** [comment]
@sam2332 Sorry for very long delay. I am back to make more changes. I don't have access to NS but can you make the similar code for regular PC gamepad. I will happily merge your code once I test that version. Thanks again for your contribution.

**Comment by sam2332** [comment]
I will mock it up tomorrow.

**Comment by sam2332** [comment]
Hi milador, I have adapted my solution for the other devices, i am unable to actually test the code as my system is not setup at this time but i made http servers for every device

**Comment by milador** [comment]
@sam2332  New API branch is now includes the fast api implementation.

**Pull request closed without merging**
